name: Test Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow, import-from-orchestrator]

env:
  CONFIGS_SAVE_PATH: .orchestrator-configs
  VARS_FILE_NAME: app-vars-set-1.yaml

permissions:
  contents: write
  actions: read

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      should_pull: ${{ steps.flag.outputs.should_pull }}
    steps:
      - id: flag
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" && "${{ github.event.action }}" == "import-from-orchestrator" ]]; then
            echo "should_pull=true"  >> "$GITHUB_OUTPUT"
          else
            echo "should_pull=false" >> "$GITHUB_OUTPUT"
          fi

  inject-config-files:
    needs: [decide]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Run Inject files
        uses: ./.github/actions/run_inject_config_files
        with:
          should_pull:      ${{ needs.decide.outputs.should_pull }}
          token:            ${{ secrets.VARS_LIST_TOKEN }}
          source_owner:     ${{ github.event.client_payload.source_owner }}
          source_repo:      ${{ github.event.client_payload.source_repo }}
          run_id:           ${{ github.event.client_payload.run_id }}
          artifact_name:    ${{ github.event.client_payload.artifact_name_files }}
          fallback_files_dir: ${{ env.CONFIGS_SAVE_PATH }}/files

  inject-config-vars:
    needs: [decide]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Run Inject vars
        uses: ./.github/actions/run_inject_config_vars
        with:
          should_pull:        ${{ needs.decide.outputs.should_pull }}
          token:              ${{ secrets.VARS_LIST_TOKEN }}
          source_owner:       ${{ github.event.client_payload.source_owner }}
          source_repo:        ${{ github.event.client_payload.source_repo }}
          run_id:             ${{ github.event.client_payload.run_id }}
          artifact_name:      ${{ github.event.client_payload.artifact_name_vars }}
          fallback_vars_dir:  ${{ env.CONFIGS_SAVE_PATH }}/vars
          vars_file_name:     ${{ env.VARS_FILE_NAME }}
