name: Test Workflow

on:
  push:
    branches: [main]
  workflow_dispatch: {} 
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Received repository_dispatch trigger-workflow"
